/**
 * Legal copy, ported verbatim from the live WordPress site on 2026-08-14 so the
 * migration does not drop it. Structure only was reformatted (the source is one
 * <p> with <br><br> breaks). Wording is unchanged, with one exception noted in
 * REVIEW.md: the live Privacy Policy linked the site name at a SiteGround staging
 * host (rise8companies.com); that now points at https://rise8companies.com.
 */

export type LegalBlock = { t: 'h' | 'p'; s: string }


export const PRIVACY_POLICY: LegalBlock[] = [
  { t: 'p', s: 'Your privacy is important to us. This Privacy Policy describes the types of information RISE8 COMPANIES LLC and their affiliates (“RISE8”) collect from you when you visit www.rise8companies.com or any other of our websites where this policy is posted (each a “Site”) or otherwise interact with us online.' },
  { t: 'p', s: 'This Privacy Policy also explains how RISE8 may use and disclose your information, as well as your ability to control certain uses of your personal information. This Privacy Policy is in addition to any separate annual Privacy Notice that RISE8 may send you under applicable privacy law.' },
  { t: 'h', s: 'INFORMATION COLLECTION' },
  { t: 'p', s: 'Information Collected About Clients and Visitors To Our Website' },
  { t: 'p', s: 'To deliver’s RISE8’s services you;' },
  { t: 'p', s: 'For recruiting, position advertising, talent management and employment purposes (recording, examination, assessment, selection, conclusion of an employment offer, and with your consent the storage in our recruitment database for a possible future offer of employment, etc.);' },
  { t: 'p', s: 'To enhance your online experience, including as a way to recognize you and welcome you to the Site or App;' },
  { t: 'p', s: 'To develop new products or services and to conduct analysis to enhance current products and services;' },
  { t: 'p', s: 'To review the usage and operations of our Site, and improve our content, products, and services;' },
  { t: 'p', s: 'To recognize your online activities over time and across different websites and devices;' },
  { t: 'p', s: 'To provide you with customized Site content, or with your consent where applicable via email, telephone, text message, by mail and other marketing channels;' },
  { t: 'p', s: 'As applicable and with your consent where applicable, to contact you with information, newsletters and promotional materials from RISE8or on behalf of our business partners, licensees, and affiliates;' },
  { t: 'p', s: 'With your consent where applicable, to serve ads or send direct messages through third party services (including social media platforms) that are targeted to reach people on those services who are identified in our data bases. This may be done by matching common factors between our data bases and the data bases of third party operators. For example, we use Facebook’s “Custom Audience” services, which allows us to provide such information on Facebook to people whose information and email addresses we already have when they expressed an interest in hearing from us;' },
  { t: 'p', s: 'To contact you when necessary, including for employment purposes, by email, telephone text message, or by mail;' },
  { t: 'p', s: 'To use your data in an aggregated non-specific format for analytical purposes;' },
  { t: 'p', s: 'To address problems with the Services, or our business;' },
  { t: 'p', s: 'To protect the security or integrity of the Site, and our business, such as by protecting against and preventing fraud, unauthorized transactions, claims and other liabilities, and managing risk exposure, including by identifying potential hackers and other unauthorized users; and' },
  { t: 'p', s: 'As otherwise described to you at the point of data collection.' },
  { t: 'p', s: 'Additionally, if you use the Site to connect with third party services you authorize us to use information from you, on your behalf, to interact with these third party services based on your requests.' },
  { t: 'h', s: 'INFORMATION SHARING' },
  { t: 'p', s: 'RISE8 may disclose the personal information we collect from you with the following categories of third parties and in the following ways:' },
  { t: 'p', s: 'With our affiliated companies;' },
  { t: 'p', s: 'With our third party service providers that provide business, professional or technical support functions for us;' },
  { t: 'p', s: 'As necessary if we believe that there has been a violation of our Terms of Use or of our rights or the rights of any third party;' },
  { t: 'p', s: 'To respond to judicial process or provide information to law enforcement or regulatory agencies or in connection with an investigation on matters related to public safety, as permitted by law, or otherwise as required by law; and' },
  { t: 'p', s: 'As otherwise described to you at the point of collection.' },
  { t: 'p', s: 'RISE8 may also share aggregate or anonymous non-personal information with third parties for marketing or analytics uses on behalf of RISE8.' },
  { t: 'p', s: 'We may share your personally identifiable information (“PII”) in connection with a merger, financing, acquisition, dissolution transaction, bankruptcy or proceeding involving sale, transfer, divestiture of all or a portion of our business or assets. If another entity acquires our business or assets, that entity will have your PII collected by us and will assume the rights and obligations regarding your information as allowed by this privacy policy.' },
  { t: 'h', s: 'LINKS TO OTHER WEBSITES' },
  { t: 'p', s: 'The Site, and email messages from us, may contain links to third-party websites, which may have privacy policies that differ from our own. You should be aware that the collection, retention and use of any data you provide on these websites will be governed by the privacy policy of the company providing the website and not by this Privacy Policy. We are not responsible for the practices of such websites.' },
  { t: 'h', s: 'PUBLIC FORUMS' },
  { t: 'p', s: 'Any information you may disclose on our Site, in blogs, on message boards, in chat rooms, or on other public areas on the Site, or other third-party websites that the Site may link to, becomes public information. Please exercise caution when disclosing personal information in these public areas. We reserve the right to remove any posting or content in a posting at our sole discretion.' },
  { t: 'h', s: 'CHILDREN’S PRIVACY' },
  { t: 'p', s: 'Protecting children’s privacy is important to us. We do not direct the Site to, nor do we knowingly collect any personal information from, children under the age of thirteen. If we learn that a child under the age of thirteen has provided personally identifiable information to the Site, we will use reasonable efforts to remove such information from its files.' },
  { t: 'h', s: 'DATA SECURITY' },
  { t: 'p', s: 'We have taken certain physical, administrative, and technical steps to safeguard the information we collect from and about our customers and Site visitors. While we make every effort to help ensure the integrity and security of our network and systems, we cannot guarantee our security measures.' },
  { t: 'h', s: 'DATA STORAGE' },
  { t: 'p', s: 'We have taken certain physical, administrative, and technical steps to safeguard the information we collect from and about our customers and Site visitors. While we make every effort to help ensure the integrity and security of our network and systems, we cannot guarantee our security measures.' },
  { t: 'h', s: 'YOUR OPTIONS AND ACCESS TO YOUR PERSONAL INFORMATION' },
  { t: 'p', s: 'To access, review, or update your information stored by RISE8,you may contact your respective RISE8 office or account representative to have them update your information in our system. If you have any additional questions concerning access to or updating your personal information, please contact us at the information provided in the “Contact Us” section below.' },
  { t: 'h', s: 'CONTACT US' },
  { t: 'p', s: 'We hope this Privacy Policy answers your questions about our collection, use and disclosure of your personal data. If you have additional questions about this Privacy Policy or the practices described herein, you may contact us at corporate@rise8companies.com' },
  { t: 'h', s: 'NON-EEA USER’S ACCEPTANCE OF THIS PRIVACY POLICY' },
  { t: 'p', s: 'By using the Services, you confirm that you have read and understood this Privacy Policy. If you do not agree with the terms of this Privacy Policy, please do not use our Services at all. You may opt out of marketing communications at any time by contacting RISE8 using the information above.' },
  { t: 'h', s: 'REVISIONS TO THIS PRIVACY POLICY' },
  { t: 'p', s: 'RISE8 reserves the right, at its sole discretion, to change, modify, add, remove, or otherwise revise portions of this Privacy Policy at anytime. If we do, we will provide access to the immediately prior version of the Privacy Policy on the Site. Your continued use of the Site following the posting of changes to these terms means you accept these changes.' },
  { t: 'p', s: 'Non-affiliated third parties are independent from RISE8 and if you wish to receive information about your disclosure choices or stop communications from such third parties, you will need to contact those non-affiliated third parties directly.' },
  { t: 'h', s: 'RISE8 DMCA COPYRIGHT POLICY' },
  { t: 'p', s: 'In conjunction with the provision and use of this website (the “Service”), RISE8 Companies LLC (“RISE8”) has adopted the following general policy toward copyright infringement in accordance with the Digital Millennium Copyright Act (http://lcweb.loc.gov/copyright/legislation/dmca.pdf). The address of RISE8’s Designated Agent to Receive Notification of Claimed Infringement (“Designated Agent”) is listed at the end of this policy. This DMCA Copyright Policy is part of the Terms of Service for the Service.' },
  { t: 'p', s: 'It is RISE8’s policy to (i) block access to or remove material that it believes in good faith to be copyrighted material that has been illegally copied and distributed by users or downloaded through RISE8’s networks; and (ii) remove and discontinue service to repeat offenders.' },
  { t: 'h', s: 'A. Procedure for Reporting Copyright Infringements:' },
  { t: 'p', s: 'If you believe that material or content residing on or accessible through the Service website or the Service, or downloaded using RISE8’s networks, infringes a copyright, please send a notice of copyright infringement containing the following information to the Designated Agent listed below:' },
  { t: 'p', s: 'A physical or electronic signature of a person authorized to act on behalf of the owner of the copyright that has been allegedly infringed;' },
  { t: 'p', s: 'Identification of works or materials being infringed;' },
  { t: 'p', s: 'Identification of the material that is claimed to be infringing, including information regarding the location of the infringing materials that the copyright owner seeks to have removed, or the date and time that the allegedly infringing material was downloaded using RISE8’s network with sufficient detail so that RISE8 is capable of finding and verifying its existence;' },
  { t: 'p', s: 'Contact information about the notifier, including address, telephone number, and, if available, e-mail address. If you are not the owner of the copyright that has been allegedly infringed, please describe your relationship to the trademark owner;' },
  { t: 'p', s: 'A statement that the notifier has a good faith belief that the material is not authorized by the copyright owner, its agent, or the law; and' },
  { t: 'p', s: 'A statement made under penalty of perjury that the information provided is accurate and the notifying party is authorized to make the complaint on behalf of the copyright owner.' },
  { t: 'h', s: 'B. Once Proper Bona Fide Infringement Notification is Received by the Designated Agent:' },
  { t: 'p', s: 'Upon receipt of a fully completed and signed notification form, RISE8 will disable access to the allegedly infringing materials and will promptly notify the individual who posted the materials that access has been disabled. If your notification is unsigned or does not contain the authorization language described above, RISE8 will work with you to obtain a properly executed notification. If any of the other information is missing from your notification, however, RISE8 will not be able to respond to your request.' },
  { t: 'h', s: 'C. Procedure to Supply a Counter-Notice to the Designated Agent:' },
  { t: 'p', s: 'If the content provider, member, or user believes that the material that was removed or to which access was disabled is either not infringing, or the content provider, member, or user believes that it has the right to post and use such material from the copyright owner, the copyright owner’s agent, or pursuant to the law, the content provider, member, or user must send a counter-notice containing the following information to the Designated Agent listed below:' },
  { t: 'p', s: 'A physical or electronic signature of the content provider, member, or user;' },
  { t: 'p', s: 'Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or disabled;' },
  { t: 'p', s: 'A statement that the content provider, member, or user has a good faith belief that the material was removed or disabled as a result of mistake or a misidentification of the material; and' },
  { t: 'p', s: 'Content provider’s, member’s, or user’s name, address, telephone number, and, if available, e-mail address and a statement that such person or entity consents to the jurisdiction of the United States District Court for the judicial district in which the content provider’s, member’s, or user’s address is located, or if the content provider’s, member’s, or user’s address is located outside the United States, for any judicial district in which RISE8 is located, and that such person or entity will accept service of process from the person who provided notification of the alleged infringement.' },
  { t: 'p', s: 'If a counter-notice is received by the Designated Agent, RISE8 may send a copy of the counter-notice to the original complaining party informing that person that it may replace the removed material or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the content provider, member, or user, the removed material may be replaced or access to it restored in 10 to 14 business days or more after receipt of the counter-notice, at RISE8’s discretion.' },
  { t: 'p', s: 'Please contact RISE8’s Designated Agent to Receive Notification of any claimed copyright infringement at the following address:' },
  { t: 'p', s: 'DMCA Agent' },
  { t: 'p', s: 'Attn: Legal Department' },
  { t: 'p', s: 'RISE8 COMPANIES' },
  { t: 'p', s: '8230 210TH ST S, Ste. 2' },
  { t: 'p', s: 'Boca Raton FL 33433' },
  { t: 'p', s: 'Email: corporate@rise8companies.com' },
  { t: 'p', s: 'RISE8’s agent information is provided pursuant to the Digital Millennium Copyright Act, 17 U.S.C. § 512(c)(2).' },
]

export const TERMS_OF_USE: LegalBlock[] = [
  { t: 'p', s: 'By accessing and/or using this web site and any materials presented herein (the “Site”), you accept in their entirety the following terms and conditions of use of the Site (the “Terms of Use”). RISE8 Companies LLC and its affiliates (collectively “RISE8”) reserve the right to change the terms, conditions and notices under which this Site is offered without notice at any time. Each access or use of the Site constitutes your agreement to be bound by the then-current terms and conditions set forth in these Terms of Use.' },
  { t: 'h', s: '1. Limited License to Use the Site:' },
  { t: 'p', s: 'Except as specifically permitted below, nothing contained in these Terms of Use or the Site either grants or will be construed to grant to you or any third party any title or interest in, or any license or right to use or reproduce, any image, text, software, code, trademark, logo or service mark contained in the Site, including without limitation the name or logo of RISE8. RISE8 reserves, and will enforce to the fullest extent possible, all rights that it may have with respect to copyright and trademark ownership of all material in the Site.' },
  { t: 'p', s: 'RISE8 grants you a limited, nonexclusive license to display and otherwise access and/or use the Site solely for your own private, non-commercial informational purposes only, and to print pages from the Site only in connection with that access and/or use. You may not modify, distribute, transmit, perform, reproduce, publish, license, create derivative works from, transfer or sell any text, graphics, logos and other source-identifying symbols, designs, icons, images, or other information, software or code obtained from the Site.' },
  { t: 'h', s: '2. No Offer of Employment:' },
  { t: 'p', s: 'The Site does not constitute an offer or promise of employment with RISE8 with respect to any employment position described on the Site. Without notice, RISE8 may eliminate, modify or change any aspects of any employment described on the Site. The Site does not provide binding offers of employment or any terms or conditions of employment. Any offer of employment that may ensue as a result of your submission of information to RISE8 shall be solely in accordance with the specific terms of such offer of employment, not the terms of the Site.' },
  { t: 'h', s: '3. No Offer of Securities:' },
  { t: 'p', s: 'Under no circumstances should any material on the Site be used or considered as an offer to sell or a solicitation of an offer to buy any interest in any investment fund sponsored or managed by RISE8’s affiliates. Any such offer or solicitation can and will be made only by means of the confidential information memorandum of each such investment fund, only in jurisdictions in which such an offer would be lawful and only to individuals who meet the investor suitability and sophistication requirements of each such investment fund, including qualifying as accredited investors within the meaning of the Securities Act of 1933, as amended. Access to information about the investment funds is similarly limited to individuals who meet the applicable investor suitability and sophistication requirements.' },
  { t: 'h', s: '4. Links to Third Party Web Sites:' },
  { t: 'p', s: 'RISE8 has not necessarily reviewed any of the web sites that may be linked to the Site, and is not responsible for their content. RISE8 is not responsible for the privacy practices of such other web sites. Your linking to or use of any off-site pages or other web sites is at your own risk. RISE8’s inclusion of links to other web sites does not imply any endorsement of the material located on or linked to by such web sites.' },
  { t: 'h', s: '5. No Warranty:' },
  { t: 'p', s: 'RISE8, AND ITS RESPECTIVE OFFICERS, DIRECTORS, PRINCIPALS, AGENTS AND EMPLOYEES MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, RELIABILITY, COMPLETENESS, SUITABILITY OR OTHER CHARACTERISTICS OF THE INFORMATION AND MATERIALS CONTAINED ON OR PRESENTED THROUGH THE SITE. ANY CONTENT OF THE SITE IS SUBJECT TO CHANGE WITHOUT NOTICE. ALL SUCH INFORMATION AND MATERIALS ARE PROVIDED “AS IS”, WITHOUT ANY WARRANTY OF ANY KIND. RISE8 HEREBY FURTHER DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH REGARD TO SUCH INFORMATION AND MATERIALS, INCLUDING ALL IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT AND AVAILABILITY.' },
  { t: 'h', s: '6. Limitation of Liability:' },
  { t: 'p', s: 'TO THE FULL EXTENT PERMITTED BY APPLICABLE LAW, RISE8, AND ITS RESPECTIVE OFFICERS, DIRECTORS, PRINCIPALS, AGENTS AND EMPLOYEES SHALL NOT BE LIABLE FOR ANY CLAIMS, LIABILITIES, LOSSES, COSTS OR DAMAGES, INCLUDING DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES, ARISING OUT OF OR IN ANY WAY CONNECTED WITH (I) THE USE OF OR INABILITY TO USE THE SITE OR WITH ANY DELAY IN USING THE SITE, OR (II) ANY INFORMATION AND MATERIALS OBTAINED THROUGH THE SITE, OR (III) OTHERWISE ARISING OUT OF THE ACCESS AND/OR USE OF THE SITE; IN ANY CASE WHETHER BASED ON THEORIES ARISING IN CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE. SUCH LIMITATIONS APPLY EVEN IF RISE8 OR ANY OF ITS RESPECTIVE OFFICERS, DIRECTORS, PRINCIPALS, AGENTS OR EMPLOYEES HAVE BEEN ADVISED OF THE POSSIBILITY OF DAMAGES.' },
  { t: 'h', s: '7. General:' },
  { t: 'p', s: 'These Terms of Use are governed by the laws of the State of Illinois, without reference to their conflicts of laws provisions. You consent to the jurisdiction of, and venue shall lie in, any federal or state court located in Palm Beach County, Florida, U.S.A., as the exclusive jurisdiction and venue for the adjudication of all disputes arising out of or relating to the use of the Site.' },
  { t: 'p', s: 'Except with regard to requests pertaining to personal information (which address is provided in the Privacy Policy any notice to RISE8 shall be given in writing and sent by registered mail to Attn: Legal Department.' },
  { t: 'p', s: 'RISE8 COMPANIES' },
  { t: 'p', s: '8230 210TH ST S, Ste. 2' },
  { t: 'p', s: 'Boca Raton FL 33433' },
  { t: 'p', s: 'Email: corporate@rise8companies.com' },
  { t: 'p', s: 'If any provision of these Terms of Use is held to be invalid or unenforceable in any jurisdiction, such provision shall be deemed modified to the minimum extent necessary so that such provision shall no longer be held to be invalid or unenforceable, and these Terms of Use shall be interpreted so as to achieve the intent expressed herein to the greatest extent possible in the jurisdiction in question. Any such modification, invalidity or unenforceability shall be strictly limited both to such provision and to such jurisdiction.' },
  { t: 'p', s: '“RISE8” and related marks, images and symbols are the exclusive properties of an affiliate of RISE8 IP LLC.' },
]
